#!/usr/bin/env bash
set -euo pipefail

tracking_worktree="${TRACKING_SO_WORKTREE:-/home/alex/workspace/tracking-so-main}"
frontend_host="${TRACKING_SO_FRONTEND_HOST:-tracking-so.95.216.185.20.nip.io}"
backend_host="${TRACKING_SO_BACKEND_HOST:-api.tracking-so.95.216.185.20.nip.io}"
supabase_host="${TRACKING_SO_SUPABASE_HOST:-supabase.tracking-so.95.216.185.20.nip.io}"
portless_port="${TRACKING_SO_PORTLESS_PORT:-1355}"
frontend_portless_name="${frontend_host%.io}"
backend_portless_name="${backend_host%.io}"

install -d "$HOME/.codex" "$HOME/.claude"

cat > "$HOME/.codex/AGENTS.override.md" <<EOF
# Hermes Machine Instructions

Generated by \`/home/alex/.hermes/hermes-agent/scripts/setup-global-agent-instructions.sh\`.

This machine is \`hermes-agent\` at Tailscale \`100.101.106.63\`. When a task concerns tracking.so / self-tracking-software, use the clean worktree at \`${tracking_worktree}\` unless the user explicitly says otherwise. Project instructions inside that worktree still apply.

## Remote Dev URLs

Report these URLs to the user after starting or restarting the dev stack:

- Frontend: https://${frontend_host}
- Backend health: https://${backend_host}/health
- Supabase API: https://${supabase_host}/rest/v1/

## Starting The Exposed Dev Stack

Use tmux sessions named \`tracking-so-backend\` and \`tracking-so-frontend\` for long-running servers.

Backend:

\`\`\`bash
cd ${tracking_worktree}
EXTRA_CORS_ORIGINS=https://${frontend_host},https://${backend_host} \\
PORTLESS_PORT=${portless_port} PORTLESS_HTTPS=0 PORTLESS_TLD=io PORTLESS_SYNC_HOSTS=0 \\
portless ${backend_portless_name} pnpm --dir apps/backend-node dev
\`\`\`

Frontend:

\`\`\`bash
cd ${tracking_worktree}
pnpm --dir apps/frontend-vite gen
VITE_BACKEND_URL=https://${backend_host} \\
VITE_SUPABASE_API_URL=https://${supabase_host} \\
PORTLESS_PORT=${portless_port} PORTLESS_HTTPS=0 PORTLESS_TLD=io PORTLESS_SYNC_HOSTS=0 \\
portless ${frontend_portless_name} bash -lc 'pnpm --dir apps/frontend-vite exec vite --host "\$HOST" --port "\$PORT"'
\`\`\`

Caddy already maps public HTTPS for these hosts to the Portless HTTP listener on \`127.0.0.1:${portless_port}\`. Tailscale Funnel is currently not available on this account because Tailscale HTTPS certificates are unsupported.

## Local Database

tracking.so uses local Supabase/Postgres on this machine:

- Supabase API: http://127.0.0.1:55321
- Postgres: localhost:55322

Verify database state with:

\`\`\`bash
cd ${tracking_worktree}
pnpm --dir packages/prisma db:status
pnpm --dir apps/backend-node query-db --query "SELECT 1 AS ok"
\`\`\`

Apply committed migrations with \`pnpm --dir packages/prisma db:deploy\`. Do not use \`prisma migrate dev\` for tracking.so on this machine.

## Disk Awareness

The VPS has about 80 GB of disk. Before large installs, Docker pulls, or generated artifacts, check \`df -h /\` and clean obvious caches or stopped containers if space is tight.
EOF

cat > "$HOME/.claude/CLAUDE.md" <<EOF
# Hermes Machine Instructions

Generated by \`/home/alex/.hermes/hermes-agent/scripts/setup-global-agent-instructions.sh\`.

This machine is \`hermes-agent\` at Tailscale \`100.101.106.63\`. When a task concerns tracking.so / self-tracking-software, use the clean worktree at \`${tracking_worktree}\` unless the user explicitly says otherwise. Project instructions inside that worktree still apply.

## Remote Dev URLs

Report these URLs to the user after starting or restarting the dev stack:

- Frontend: https://${frontend_host}
- Backend health: https://${backend_host}/health
- Supabase API: https://${supabase_host}/rest/v1/

## Starting The Exposed Dev Stack

Use tmux sessions named \`tracking-so-backend\` and \`tracking-so-frontend\` for long-running servers.

Backend:

\`\`\`bash
cd ${tracking_worktree}
EXTRA_CORS_ORIGINS=https://${frontend_host},https://${backend_host} \\
PORTLESS_PORT=${portless_port} PORTLESS_HTTPS=0 PORTLESS_TLD=io PORTLESS_SYNC_HOSTS=0 \\
portless ${backend_portless_name} pnpm --dir apps/backend-node dev
\`\`\`

Frontend:

\`\`\`bash
cd ${tracking_worktree}
pnpm --dir apps/frontend-vite gen
VITE_BACKEND_URL=https://${backend_host} \\
VITE_SUPABASE_API_URL=https://${supabase_host} \\
PORTLESS_PORT=${portless_port} PORTLESS_HTTPS=0 PORTLESS_TLD=io PORTLESS_SYNC_HOSTS=0 \\
portless ${frontend_portless_name} bash -lc 'pnpm --dir apps/frontend-vite exec vite --host "\$HOST" --port "\$PORT"'
\`\`\`

Caddy already maps public HTTPS for these hosts to the Portless HTTP listener on \`127.0.0.1:${portless_port}\`. Tailscale Funnel is currently not available on this account because Tailscale HTTPS certificates are unsupported.

## Local Database

tracking.so uses local Supabase/Postgres on this machine:

- Supabase API: http://127.0.0.1:55321
- Postgres: localhost:55322

Verify database state with:

\`\`\`bash
cd ${tracking_worktree}
pnpm --dir packages/prisma db:status
pnpm --dir apps/backend-node query-db --query "SELECT 1 AS ok"
\`\`\`

Apply committed migrations with \`pnpm --dir packages/prisma db:deploy\`. Do not use \`prisma migrate dev\` for tracking.so on this machine.

## Disk Awareness

The VPS has about 80 GB of disk. Before large installs, Docker pulls, or generated artifacts, check \`df -h /\` and clean obvious caches or stopped containers if space is tight.
EOF

chmod 0644 "$HOME/.codex/AGENTS.override.md" "$HOME/.claude/CLAUDE.md"
printf 'Installed global agent instructions:\n  %s\n  %s\n' "$HOME/.codex/AGENTS.override.md" "$HOME/.claude/CLAUDE.md"
